#!/usr/bin/env bash
# Changes localhost and facebook.com IP resolution

# Backup original hosts file (optional but recommended)
cp /etc/hosts /etc/hosts/bak

# Overwrite hosts file wuth required configuration
echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
